apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-deployment
  labels:
    app: greeting
spec:
  replicas: 1
  selector:
      matchLabels:
        name: greeting
  template:
    metadata:
      labels:
        app: greeting
    spec:
      containers:
      - name: greeting
        image: host.minikube.internal:5000/greeting
        imagePullPolicy: Always
