apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: greeting-ingress
  labels:
    app: greeting
spec:
    rules:
    - host: greeting.info
      http:
          paths:
          - path: /
            backend:
                serviceName: greeting-service
                servicePort: 8080
