apiVersion: v1
kind: Service
metadata:
    name: greeting-service
    labels:
      app: greeting
spec:
    selector:
        app: greeting
    ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
    type: NodePort
