apiVersion: v1
kind: Service
metadata:
    labels:
      app: greeting
    name: greeting
spec:
    selector:
        app: greeting
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
